# This is a basic workflow to help you get started with Actions

name: CI-trigger

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      update-internal:
        description: "update internal source code or not"
        required: true
        default: "false"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  info:
    runs-on: ubuntu-latest
    outputs:
      is_rerun_failed: ${{ steps.set-rerun.outputs.is_rerun_failed }}
    steps:
      - id: set-rerun
        name: get is rerun
        run: |
          echo run this job means run all jobs!
          echo "is_rerun_failed=true" >> "$GITHUB_OUTPUT"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: info

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          is_rerun_failed: ${{ needs.info.outputs.is_rerun_failed }}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Event action: ${{ github.event.action }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Workflow run ID: ${{ github.run_id }}"
          echo "Run attempt: ${{ github.run_attempt }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run number: ${{ github.run_number }}"
          echo "is_rerun_failed: $is_rerun_failed"
          if [ "${{ needs.info.result }}" = "skipped" ]; then
            echo "⚠️ prepare job was skipped, not executed."
            exit 1
          elif [ "${{ needs.info.result }}" = "success" ]; then
            echo "✅ prepare job executed successfully."
          else
            echo "❌ prepare job failed."
            exit 1
          fi

      - name: Run a one-line script
        run: |
          echo Hello, world!
          sh ./test.sh
  
